### ISSUE TITLE
"Run in the Platform" is worthless

### ISSUE THREAD

**Issue by bendalton** [Telerik-Verified-Plugins/Toast-DemoApp#2]
Based on the language and position on the page, it implies that you can preview this feature.

6 clicks and 3 minutes later, I'm viewing the sample app in the "simulator" and click to test one of the toasts only to be greeted with "This plugin is not available in the simulator".

IF it is impossible to preview in the simulator, then you should not promote this action as a way to preview the functionality. This was a waste of my time AND left me annoyed at your "platform".

**Comment by bendalton** [comment]
I should add that there is value in "Run in the Platform" as a quick way to build the test app for deployment on a device. I would just make it clear that this is where the value is.

**Comment by EddyVerbruggen** [comment]
Native features are never available on a cloud simulator. If the plugin would support the browser by rendering some piece of HTML it would not be representative of how iOS/Android would render it.
