### ISSUE TITLE
Screenshots don't show toasts

### ISSUE THREAD

**Issue by bendalton** [Telerik-Verified-Plugins/Toast-DemoApp#3]
The screenshots (all 18 of them) contain useless information. Just showing that the sample app runs does not help someone understand how "Toasts" (the point of the app) function.

Please consider showing the toasts in the screenshots to hint at the functionality the app is intended to demo. Showing screens with buttons of various themes/platforms is not useful.

**Comment by EddyVerbruggen** [comment]
This is the repo of the demo, the plugin is [here](https://github.com/Telerik-Verified-Plugins/Toast) and includes screenshots of Toasts.
